version: "3.7"

services:
  chessdb_api:
    container_name: chessdb_api
    build:
      context: .
      dockerfile: docker/Dockerfile
      network: host
    command: uvicorn --reload chessdb_api.asgi:app --port 8000 --host 0.0.0.0
    environment:
      - POSTGRES_HOST=chessdb_api_db
    depends_on:
      - chessdb_api_db
    ports:
      - 12001:8000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    networks:
      - chessdb
      - chessdb_api_internal
  chessdb_api_db:
    image: postgres:12-alpine
    container_name: chessdb_api_db
    env_file:
      - .env
    volumes:
      - /tmp/chessdb_api/postgres/data:/var/lib/postgresql/data/
    networks:
      - chessdb_api_internal

networks:
  chessdb_api_internal:
  chessdb:
